import type {Locale} from '../task-engine/index.ts';
export function membersCopy(locale:Locale){
  const t=(zh:string,en:string)=>locale==='en'?en:zh;
  return {
    title:t('家长协作','Parents together'),intro:t('为每位家长保留独立账号。邀请加入后，还需要家庭创建者确认。','Each parent has a separate account. The family creator confirms access after an invitation is accepted.'),
    scope:t('协作家长可以陪伴所选孩子练习、查看练习记录并添加日常观察。生活目标与回顾、导出删除和家庭权限仍由创建者管理。','Supporting parents can start practice for selected children, view practice records and add everyday observations. Everyday goals and reflections, exports, deletion and family access stay with the creator.'),
    invite:t('邀请一位家长','Invite a parent'),select:t('选择可陪伴的孩子','Choose children to support'),ackInvite:t('我认识这位家长，并同意向其开放所选孩子的上述权限。','I know this parent and agree to share the access described above for the selected children.'),
    code:t('邀请码只显示这一次','This invitation code is shown once'),codeHelp:t('请自行交给你认识的家长，在登录页选择“接受邀请”。48 小时内有效；接受后仍需你确认。刷新或离开后无法再次查看，可取消旧邀请再创建。','Give this code privately to the parent you know. They choose “Accept invitation” on the sign-in page. It lasts 48 hours and still needs your confirmation after acceptance. Reloading or leaving hides the code; cancel and replace an unused invitation if needed.'),
    member:t('家长登录名','Parent username'),memberHint:t('创建者填写 owner；受邀家长填写自己设置的登录名。','Creators use owner; invited parents use the username they chose.'),display:t('家长称呼','Parent display name'),password:t('设置自己的密码','Choose your own password'),repeat:t('再次输入密码','Repeat password'),passwordHint:t('至少 15 个字符。登录名使用 3–32 个英文字母、数字或 . _ -。','Use at least 15 password characters. Usernames use 3–32 letters, numbers or . _ -.'),
    join:t('接受邀请','Accept invitation'),joinCode:t('邀请码','Invitation code'),joinIntro:t('建立自己的协作账号，然后等待家庭创建者确认。此步骤不会授予监护身份。','Create your own supporting account, then wait for the family creator to confirm. This does not verify legal guardianship.'),
    localAck:t('我知道这是本机开发体验，使用虚构资料，并同意先由创建者确认访问。','I understand this is a local preview using fictional details, with creator confirmation before access.'),
    pendingTitle:t('等待家庭创建者确认','Waiting for the family creator'),pending:t('已收到加入申请。请与创建者核对你的登录名；确认之前，这里不会显示孩子资料。','Your request is saved. Check your username with the creator. Child records stay hidden until they confirm.'),
    owner:t('家庭创建者','Family creator'),support:t('协作家长','Supporting parent'),active:t('已开放','Active'),revoked:t('已撤销','Revoked'),pendingLabel:t('待确认','Waiting for confirmation'),allChildren:t('所有孩子','All children'),noChildren:t('当前无可访问的孩子，请联系创建者。','No children are currently available. Contact the creator.'),
    approve:t('确认这位家长','Confirm this parent'),revoke:t('撤销访问','Revoke access'),ackApprove:t('我已与对方核对登录名，确认是我邀请的家长，并同意开放所列孩子的权限。','I checked this username with the person I invited and approve the listed access.'),
    ackRevoke:t('我确认结束这位家长的访问及其登录。已保存记录保留；离线设备联网后才能收到通知。','I understand this ends this parent’s access and sign-ins. Saved records remain; offline devices learn about the change when they reconnect.'),
    invitations:t('最近的邀请','Recent invitations'),open:t('待接受','Not yet accepted'),expired:t('已过期','Expired'),accepted:t('已接受','Accepted'),cancelled:t('已取消','Cancelled'),cancelInvite:t('取消邀请','Cancel invitation'),ackCancel:t('我确认取消这份尚未接受的邀请。','I confirm cancellation of this unused invitation.'),
    confirm:t('确认操作','Confirm'),cancel:t('返回','Back'),reload:t('重新读取','Reload'),loading:t('正在读取…','Loading…'),busy:t('正在保存…','Saving…'),signin:t('重新验证家长身份','Verify parent sign-in'),logout:t('退出登录','Sign out'),
    error:(code:string)=>({MEMBER_VERSION_CONFLICT:t('权限已更新，请重新读取后确认。','Access changed. Reload before confirming.'),MEMBER_CHILDREN_UNAVAILABLE:t('部分孩子已停止采集或不可用，请重新选择。','Some children are unavailable. Reload and choose again.'),MEMBER_LIMIT:t('最多四位家长，待接受的邀请也占名额。请先处理已有邀请。','Up to four parents, including unused invitations. Review existing invitations first.'),INVITE_ALREADY_CREATED:t('邀请可能已经创建。请查看列表；若没有保留邀请码，取消旧邀请后再创建。','An invitation already exists. Check the list; cancel and replace it if the code was not retained.'),INVITE_ACCEPTED:t('对方已接受，请在家长列表中处理。','Already accepted. Use the parent list to manage access.'),RESULT_UNCONFIRMED:t('尚未确认保存结果，请重新读取列表后再操作。','The result is unconfirmed. Reload the list before another action.'),INVITE_UNAVAILABLE:t('邀请不可用，可能已过期、取消或接受。','This invitation is unavailable; it may have expired, been cancelled or been accepted.'),MEMBER_NAME_TAKEN:t('此家庭已有这个登录名，请换一个。','That username is already used in this family. Choose another.'),REAUTH_REQUIRED:t('请重新验证家长身份后操作。','Verify your parent sign-in before continuing.'),INVALID_REQUEST:t('请检查登录名、密码和确认选项。','Check the username, password and confirmation.'),OWNER_REQUIRED:t('此操作由家庭创建者管理。','The family creator manages this action.')}[code]??t('暂时无法完成，请重新读取或登录后再试。','Unable to continue. Reload or sign in again.')),
  };
}
