import {useCallback,useEffect,useState} from 'react';
import {Text,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import type {Locale} from '../../../packages/task-engine/index.ts';
import type {RecoveryItem} from '../../../packages/session-runtime/recovery-model.ts';
import {useRecovery} from '../../../packages/session-runtime/useRecovery.ts';
import {recoveryCopy} from '../../../packages/session-runtime/recovery-copy.ts';
import {translate,taskContent} from '../../../packages/content/copy.ts';
import {MobileClient} from './client';
import {Page,Button,CheckBox,Notice,s} from './ui';
export function Recovery({childId,locale,client,onResume,onBack,onRequireLogin}:{childId:string;locale:Locale;client:MobileClient;onResume(id:string):Promise<void>;onBack():void;onRequireLogin():void}){
 const t=translate(locale),request=useCallback(client.request.bind(client),[client]),device=useCallback(()=>client.deviceId(),[client]);
 const {state,reload,handover,resume}=useRecovery(childId,request,device,randomUUID),[confirmed,setConfirmed]=useState(false),data=state.data,active=data?.active;
 useEffect(()=>setConfirmed(false),[active?.etag,state.saved,state.error]);
 const description=(item:RecoveryItem)=><><Text style={s.heading}>{taskContent(item.task,locale).title}</Text><Text style={s.muted}>{new Date(item.createdAt).toLocaleString(locale)} · {item.sameDevice?t('此设备','This device'):t('另一台设备','Another device')} · {item.environment?.platform??'Legacy'}</Text><Text style={s.body}>{t(`服务端已收到 ${item.receivedEvents} 条操作记录，不代表本机记录都已上传。`,`The service received ${item.receivedEvents} events. This may not include all local records.`)}</Text>{item.uploadUntil&&<Text style={s.muted}>{t('补传截止：','Upload deadline: ')}{new Date(item.uploadUntil).toLocaleString(locale)}</Text>}{item.mayResume===false&&<Notice>{t('这次旧练习的开放范围已改变，不能恢复或补传；本机记录仍可导出。','The release scope for this earlier practice changed. It cannot resume or upload; local records remain exportable.')}</Notice>}</>;
 const resumeButton=(item:RecoveryItem)=>item.sameDevice&&!item.finalized&&<Button quiet disabled={state.busy||!data?.collectionActive||item.mayResume===false} title={item.historyOnly?t('恢复本机记录并补传','Recover and upload local records'):t('回到此设备的练习','Resume on this device')} onPress={()=>void resume(item,onResume)} />;
 return <Page title={t('未结束练习与换设备','Unfinished practice & changing devices')}><Button quiet title={t('返回家庭空间','Back to family space')} onPress={onBack} /><Text style={s.body}>{t('先在原设备结束并同步，可以保留记录。原设备不在身边时，家长也可以结束旧练习，之后补传的记录会单独保存。','End and sync on the original device to preserve its record. If it is unavailable, a parent can end the old practice here; later uploads will be saved separately.')}</Text><Button quiet disabled={state.busy} title={t('刷新状态','Refresh status')} onPress={()=>void reload()} />
 {state.busy&&<Text accessibilityLiveRegion="polite" style={s.muted}>{t('正在确认记录…','Checking records…')}</Text>}
 <Notice>{state.saved?t('旧练习已结束。已有记录可以单独补传，不计入课程。','The old practice has ended. Saved records may still be uploaded separately without changing the course.'):''}</Notice><Notice>{recoveryCopy(locale,state.error)}</Notice>
 {['REAUTH_REQUIRED','UNAUTHENTICATED','PARENT_REQUIRED'].includes(state.error)&&<Button title={t('验证家长密码','Verify parent password')} onPress={onRequireLogin} />}
 {data&&<><Text style={s.muted}>{data.budgetDay} · {data.timezone} · {t(`尚未分配的练习额度约 ${Math.floor(data.availableMs/60000)} 分钟。`,`About ${Math.floor(data.availableMs/60000)} minutes of unallocated allowance.`)}</Text>{!data.collectionActive&&<Notice>{t('此档案已停止采集。','Collection has stopped for this profile.')}</Notice>}{data.marketOpen===false&&<Notice>{t('当前地区、年龄或语言尚未开放新练习。已有记录仍可导出。','New practices are unavailable for this region, age or language. Existing records remain exportable.')}</Notice>}
 {active?<View style={s.card}>{description(active)}{resumeButton(active)}{active.handoverAvailable?<><Text style={s.heading}>{t('由家长结束旧练习','End the old practice as a parent')}</Text><Text style={s.body}>{t('旧设备断网时不能立即收到通知，原设备确认补传和结束前，当天额度会继续预留；确认后释放未用部分。无法确认且没有剩余额度时，今天先休息，明天再开始。旧记录单独保存，不推进课程、不调整难度。','An offline device cannot receive this change immediately. Its allowance stays reserved until the original device confirms upload and closure, then the unused part is released. Otherwise, if none remains, take a break today and start tomorrow. Old records stay separate without changing the course or difficulty.')}</Text><CheckBox disabled={state.busy||!data.collectionActive} value={confirmed} onChange={value=>{if(!state.busy&&data.collectionActive)setConfirmed(value)}} label={t('我已了解额度与旧记录的处理方式，确认结束这份练习。','I understand the allowance and record handling, and confirm ending this practice.')} /><Button disabled={!confirmed||state.busy||!data.collectionActive} title={t('确认结束旧练习','Confirm ending old practice')} onPress={()=>void handover(active)} /></>:<Notice>{t('这份旧版练习需要在原设备结束。','This legacy practice must be ended on its original device.')}</Notice>}</View>:<Text style={s.body}>{t('当前没有未结束的练习。回到首页选择下一步。','There is no unfinished practice. Return home to choose your next step.')}</Text>}
 {!!data.history.length&&<><Text style={s.heading}>{t('换设备前的独立记录','Previous-device records')}</Text><Text style={s.muted}>{t('显示最近 20 份，全部记录可从资料入口导出。','Showing the latest 20. All records are available through data export.')}</Text>{data.history.map(item=><View style={s.card} key={item.id}>{description(item)}<Text style={s.body}>{item.finalized?t('已核对保存，不计入课程或周回顾比较。','Confirmed and saved; excluded from the course and weekly comparisons.'):t('等待原设备补传或确认结束。','Awaiting upload or closure from the original device.')}</Text>{resumeButton(item)}</View>)}</>}
 </>}
 </Page>;
}
