// Generated by Azure Speech once; runtime playback is local-only.
export const GENERATED_VOICE_ASSETS = true;
export const VOICE_ASSETS = {
  "home-welcome": {
    "text": "欢迎来到小小专注岛。今天，我们只做一件小事。",
    "path": "/src/audio/home-welcome.mp3"
  },
  "search-rule": {
    "text": "找出所有的小兔子。找完以后，点找好了。",
    "path": "/src/audio/search-rule.mp3"
  },
  "search-strategy": {
    "text": "一行一行找，找完再检查。",
    "path": "/src/audio/search-strategy.mp3"
  },
  "stop-rule": {
    "text": "小兔出现，点请过桥。狐狸出现，等它自己离开。",
    "path": "/src/audio/stop-rule.mp3"
  },
  "stop-strategy": {
    "text": "先认清是谁，再决定要不要动手。",
    "path": "/src/audio/stop-strategy.mp3"
  },
  "memory-rule": {
    "text": "先看包裹的顺序，记好以后，按同样的顺序点选。",
    "path": "/src/audio/memory-rule.mp3"
  },
  "memory-strategy": {
    "text": "在心里说一遍，再按顺序行动。",
    "path": "/src/audio/memory-strategy.mp3"
  },
  "memory-recall": {
    "text": "请按刚才记住的顺序，点选包裹。",
    "path": "/src/audio/memory-recall.mp3"
  },
  "practice-start": {
    "text": "先试一小轮。弄懂规则以后，再开始。",
    "path": "/src/audio/practice-start.mp3"
  },
  "sound-on": {
    "text": "语音已开启，慢慢来。",
    "path": "/src/audio/sound-on.mp3"
  },
  "search-success": {
    "text": "小兔子都找到啦！",
    "path": "/src/audio/search-success.mp3"
  },
  "search-coach": {
    "text": "再记住一个办法：一行一行找。",
    "path": "/src/audio/search-coach.mp3"
  },
  "stop-success": {
    "text": "你会看清再行动啦！",
    "path": "/src/audio/stop-success.mp3"
  },
  "stop-coach": {
    "text": "遇到狐狸，让它自己离开。",
    "path": "/src/audio/stop-coach.mp3"
  },
  "memory-success": {
    "text": "包裹按顺序送到啦！",
    "path": "/src/audio/memory-success.mp3"
  },
  "memory-coach": {
    "text": "下次试试，在心里说一遍顺序。",
    "path": "/src/audio/memory-coach.mp3"
  }
};
