import { useEffect,useRef,useState } from 'react';
import type { FormEvent } from 'react';
import { Leaf,ArrowRight,RefreshCw,LogOut,ShieldCheck,FileCheck2,Headphones,Image as ImageIcon,History,ChevronRight,LockKeyhole } from 'lucide-react';
import {SupportContent} from './SupportContent.tsx';
import {MediaLibrary,MediaProvenance} from './MediaLibrary.tsx';
import type {LibraryMedia} from '../../../packages/content/media-library.ts';
import {environmentFor} from '../../family-web/src/api.ts';
import type {CandidatePreview,PreviewReceipt} from '../../../packages/content/preview.ts';
import type { ContentPack } from '../../../packages/content/index.ts';
type Role='editor'|'method-reviewer'|'language-reviewer'|'publisher';
type User={id:string;name:string;role:Role};
type Row={id:string;version:number;state:string;round:number;content_version:string;title:string;locale:string;age_band:string;updated_at:string};
type Source={hash:string;pack_id:string;version:string;state:string;channel:string;title:string;locale:string;age_band:string};
type PreviewRow={id:string;actor:string;round:number;pack_hash:string;level:string;seed:string;environment:{input:string};receipt:PreviewReceipt|null};
type Detail={mediaSources:Pick<LibraryMedia,'id'|'metadata'|'source_hash'|'inspection'>[];previews:PreviewRow[];draft:{id:string;author:string;pack:ContentPack;version:number;round:number;state:string;candidate_hash:string|null;published_hash:string|null};source:ContentPack;reviews:{id:string;round:number;role:Role;decision:string;pack_hash:string;preview_id:string|null;note:string;checks:{audioReviewedHashes?:string[]};name:string;created_at:string}[];history:{action:string;at:string;name:string;detail:Record<string,unknown>}[]};
const roleNames:Record<Role,string>={editor:'内容编辑','method-reviewer':'方法审核','language-reviewer':'语言与适龄审核',publisher:'发布管理'};
const states:Record<string,string>={draft:'编辑中','in-review':'待双人审核','changes-requested':'需修改',ready:'可发布预览',published:'预览已发布',recalled:'已召回'};
const actions:Record<string,string>={'preview-started':'准备候选试玩','preview-finished':'核对试玩记录','draft-media-attached':'换用导入素材','draft-reopened':'撤回并重新编辑','draft-created':'建立新版本','draft-edited':'修改内容',submitted:'冻结并提交','changes-requested':'退回修改','review-approved':'审核通过','preview-published':'发布本地预览','preview-recalled':'召回预览'};
const copyLabels:Record<'title'|'skill'|'rule'|'strategy'|'transfer',string>={title:'任务名称',skill:'练习策略',rule:'规则说明',strategy:'给孩子的小提示',transfer:'带到生活中的实践'};
const own=crypto.randomUUID();let csrf='';
const draftRoute=(id:string)=>history.replaceState(null,'','/?draft='+encodeURIComponent(id));
class HttpError extends Error{code:string;constructor(code:string,message:string){super(message);this.code=code;}}
async function request<T>(path:string,method='GET',data?:unknown,headers:Record<string,string>={}):Promise<T>{
  const response=await fetch('/api/studio'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...headers},...(data===undefined?{}:{body:JSON.stringify(data)}),signal:AbortSignal.timeout(15000)});
  const value=await response.json();if(!response.ok)throw new HttpError(value.code,value.message);if(value.csrf)csrf=value.csrf;return value;
}
const announce=()=>{const channel=new BroadcastChannel('focus-studio-access');channel.postMessage({source:own});channel.close();};
function ReviewAudio({src,onComplete}:{src:string;onComplete:()=>void}){
  const skipped=useRef(false);
  return <audio controls preload="none" src={src}
    onPlay={event=>{if(event.currentTarget.currentTime<0.25)skipped.current=false;}}
    onSeeking={event=>{if(event.currentTarget.currentTime>0.25)skipped.current=true;}}
    onEnded={event=>{const player=event.currentTarget;if(!skipped.current&&Number.isFinite(player.duration)&&player.currentTime>=player.duration-0.25)onComplete();}}/>;
}
export function App(){
  const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [library,setLibrary]=useState<LibraryMedia[]>([]);
  const [playedAudio,setPlayedAudio]=useState<{key:string;hashes:string[]}>({key:'',hashes:[]});
  const [rows,setRows]=useState<Row[]>([]),[catalogue,setCatalogue]=useState<Source[]>([]),[selected,setSelected]=useState<Detail|null>(null),[tab,setTab]=useState<'queue'|'new'|'library'|'support'>('queue'),[filter,setFilter]=useState('all');
  const [dirty,setDirty]=useState(false),[formReset,setFormReset]=useState(0);
  const [reauth,setReauth]=useState(false),[loginName,setLoginName]=useState('');const identity=useRef(0),readVersion=useRef(0),attempt=useRef<{body:string;key:string}|null>(null),previewAttempt=useRef<{body:string;key:string}|null>(null);
  const refresh=async()=>{const captured=++identity.current;setSelected(null);setDirty(false);setError('');setLoading(true);try{const me=await request<{user:User}>('/me');if(captured!==identity.current)return;setUser(me.user);const [a,b,c]=await Promise.all([request<{drafts:Row[]}>('/drafts'),request<{releases:Source[]}>('/catalogue'),request<{items:LibraryMedia[]}>('/library')]);if(captured===identity.current){setRows(a.drafts);setCatalogue(b.releases);setLibrary(c.items);const id=new URLSearchParams(location.search).get('draft');if(id){const detail=await request<Detail>('/drafts/'+encodeURIComponent(id));if(captured===identity.current)setSelected(detail);}}}catch(e){if(captured===identity.current){setUser(null);if(!(e instanceof HttpError&&e.code==='STUDIO_UNAUTHENTICATED'))setError(e instanceof Error?e.message:'暂时无法连接工作台。');}}finally{if(captured===identity.current)setLoading(false);}};
  useEffect(()=>{void refresh();const channel=new BroadcastChannel('focus-studio-access');channel.onmessage=e=>{if(e.data?.source!==own)void refresh();};return()=>{identity.current++;channel.close();};},[]);
  async function safely(fn:()=>Promise<void>){if(pending)return;setPending(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作未完成，请重试。');if(e instanceof HttpError&&e.code==='STUDIO_REAUTH_REQUIRED')setReauth(true);if(e instanceof HttpError&&e.code==='STUDIO_UNAUTHENTICATED'){identity.current++;setUser(null);setSelected(null);}}finally{setPending(false);}}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=new FormData(e.currentTarget);await safely(async()=>{await request(reauth?'/auth/reauth':'/auth/login','POST',{login:fields.get('login'),password:fields.get('password'),code:fields.get('code')});setLoginName(String(fields.get('login')));setReauth(false);announce();if(!user)await refresh();else setNotice('身份已重新验证，请核对当前内容后继续操作。');});}
  async function open(id:string){if(dirty){setError('请先保存本稿修改，或明确放弃未保存的修改。');return;}const read=++readVersion.current,scope=identity.current;await safely(async()=>{const data=await request<Detail>('/drafts/'+id);if(read===readVersion.current&&scope===identity.current){setSelected(data);draftRoute(data.draft.id);setDirty(false);setTab('queue');}});}
  async function act(path:string,method:string,data:unknown,match?:number){const body=JSON.stringify({path,method,data,match}),scope=identity.current;if(attempt.current?.body!==body)attempt.current={body,key:crypto.randomUUID()};const result=await request<Detail>(path,method,data,{'Idempotency-Key':attempt.current.key,...(match===undefined?{}:{'If-Match':`"${match}"`})});if(scope!==identity.current)return;attempt.current=null;setSelected(result);draftRoute(result.draft.id);setDirty(false);setTab('queue');const queue=await request<{drafts:Row[]}>('/drafts');if(scope!==identity.current)return;setRows(queue.drafts);setNotice('操作已保存。审核与发布只针对页面显示的这个版本。');}
  const refreshLibrary=async()=>{const scope=identity.current,data=await request<{items:LibraryMedia[]}>('/library');if(scope===identity.current)setLibrary(data.items);};
  const upload=async(path:string,file:File,mime:string)=>{const response=await fetch('/api/studio'+path,{method:'PUT',credentials:'same-origin',headers:{'Content-Type':mime,'X-CSRF-Token':csrf},body:file,signal:AbortSignal.timeout(45000)});const data=await response.json();if(!response.ok)throw new HttpError(data.code,data.message);return data as LibraryMedia;};
  const credentials=<form className="form-stack" onSubmit={login}><label>工作台账号<input name="login" required autoComplete="username" defaultValue={loginName}/></label><label>密码<input type="password" name="password" required autoComplete="current-password"/></label><label>动态验证码<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} minLength={6} autoComplete="one-time-code" required placeholder="6 位数字"/></label><button className="primary" disabled={pending}>{pending?'正在验证…':reauth?'验证身份':'进入内容工作台'}<ArrowRight size={18}/></button></form>;
  if(loading)return <main className="loading"><Leaf size={28}/><p>正在打开内容工作台…</p></main>;
  if(!user)return <main className="login-layout"><section className="login-story"><div className="wordmark"><Leaf/> 专注岛 <span>CONTENT STUDIO</span></div><p className="eyebrow">MAKE EVERY INSTRUCTION COUNT</p><h1>好的体验，<br/>从每一句指引开始。</h1><p>规则、图像、声音和生活实践，纳入可追溯的发布流程。让每次发布都有依据，每次修改都有记录。</p><div className="login-steps"><span>01 编辑</span><span>02 独立审阅</span><span>03 签名与召回</span></div></section><section className="login-card"><span className="badge">团队工作台 · 本地预览</span><h2>开始今天的内容工作</h2><p className="muted">请使用管理员分配的工作台账号。家庭账号不能用于这里。</p>{credentials}{error&&<p className="error" role="alert">{error}</p>}<button className="text-button" onClick={()=>void refresh()}>重新读取登录状态</button><p className="security-note"><ShieldCheck size={18}/>密码和动态验证码共同验证身份。当前环境只发布本地预览内容。</p></section></main>;
  const filtered=rows.filter(r=>filter==='all'||r.state===filter),d=selected?.draft,p=d?.pack;
  const reviewKey=d?`${d.id}:${d.round}:${d.candidate_hash??''}`:'',reviewedAudio=playedAudio.key===reviewKey?playedAudio.hashes:[];
  return <div className="studio-layout"><aside className="sidebar"><div className="wordmark"><Leaf/> 专注岛<span>CONTENT STUDIO</span></div><p className="nav-title">内容管理</p><button className={tab==='queue'?'nav active':'nav'} disabled={dirty||pending} onClick={()=>setTab('queue')}><FileCheck2 size={19}/>内容与审核<span>{rows.length}</span></button>{user.role==='editor'&&<button className={tab==='new'?'nav active':'nav'} disabled={dirty||pending} onClick={()=>setTab('new')}><ImageIcon size={19}/>建立新版本</button>}<button className={tab==='library'?'nav active':'nav'} disabled={dirty||pending} onClick={()=>setTab('library')}><Headphones size={19}/>图像与声音库</button><button className={tab==='support'?'nav active':'nav'} disabled={dirty||pending} onClick={()=>setTab('support')}><FileCheck2 size={19}/>家长课与生活任务</button><div className="sidebar-note"><LockKeyhole size={20}/><p>每份批准绑定内容摘要。<br/>改过的内容，重新审核。</p></div><div className="identity"><strong>{user.name}</strong><span>{roleNames[user.role]}</span><button className="text-button" onClick={()=>setReauth(!reauth)}>重新验证身份</button><button className="text-button" disabled={pending||dirty} onClick={()=>void safely(async()=>{await request('/auth/logout','POST',{});identity.current++;setUser(null);setSelected(null);csrf='';announce();})}><LogOut size={14}/>退出工作台</button></div></aside><div className="studio-main"><header className="topbar"><span>内容工作台 <ChevronRight size={14}/> {tab==='support'?'家长课与生活任务':tab==='new'?'建立新版本':tab==='library'?'图像与声音库':'版本与审核'}</span><span className="badge">LOCAL · 无商业市场开放</span></header><main className="workspace"><div className="heading"><div><p className="eyebrow">THOUGHTFUL CONTENT, TRACEABLE DECISIONS</p><h1>{tab==='support'?'让家庭指导，也有完整的审阅记录。':tab==='new'?'为下一次体验，准备新版本。':tab==='library'?'为每一份素材，保留清楚的来处。':'把每一次发布，做得清清楚楚。'}</h1><p className="muted">编辑、方法审核、语言审核与发布各有职责。当前素材仍需真实专业人员审阅。</p></div><button className="quiet" onClick={()=>void refresh()} disabled={pending||dirty}><RefreshCw size={16}/>重新读取</button></div>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}{reauth&&<section className="panel reauth"><h2>重新验证当前管理身份</h2><p className="muted">审核、发布与召回需要最近 10 分钟内完成的验证。请使用新一轮验证码。</p>{credentials}<button className="text-button" onClick={()=>setReauth(false)}>暂时返回</button></section>}
    {tab==='support'?<SupportContent key={user.id} user={user} request={request} run={safely} pending={pending} onDirty={setDirty}/>:tab==='library'?<MediaLibrary key={user.id} items={library} canEdit={user.role==='editor'} pending={pending} request={request} upload={upload} run={safely} refresh={refreshLibrary} onDirty={setDirty}/>:tab==='new'&&user.role==='editor'?<section className="panel new-version"><span className="eyebrow">VERSION FIRST</span><h2>从现有内容建立草稿</h2><p>旧版将原样保留。新草稿可修改文案；已配语音的句子变更后，必须先移除旧语音，避免声音与文字不一致。</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void safely(()=>act('/drafts','POST',{sourceHash:f.get('source'),version:f.get('version')}));}}><label>内容来源<select name="source" required>{catalogue.filter(s=>s.state==='active').map(s=><option key={s.hash} value={s.hash}>{s.title} · {s.age_band} 岁 · {s.locale} · {s.version}</option>)}</select></label><label>新版本号<input name="version" required placeholder="例如 0.15.0-preview" pattern="[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.\-]+)?"/></label><button className="primary" disabled={pending||!catalogue.length}>建立独立草稿<ArrowRight size={18}/></button></form></section>:<div className="content-columns"><section className="queue panel"><div className="queue-title"><h2>工作队列</h2><span>{filtered.length}</span></div><label className="filter-label">筛选状态<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部状态</option>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{filtered.length?filtered.map(r=><button key={r.id} disabled={pending} className={'queue-item '+(d?.id===r.id?'selected':'')} onClick={()=>void open(r.id)}><span className={'status '+r.state}>{states[r.state]}</span><strong>{r.title}</strong><span>{r.age_band} 岁 · {r.locale}</span><small>{r.content_version} · 第 {r.round} 稿</small><ChevronRight size={16}/></button>):<div className="empty"><FileCheck2 size={28}/><p>这里还没有相应内容。</p><small>{user.role==='editor'?'从现有内容建立一个新版本。':'等待编辑提交，或调整状态筛选。'}</small></div>}<p className="queue-foot">显示最近 100 份草稿</p></section><section className="detail">{!selected||!p||!d?<div className="panel detail-empty"><Leaf size={34}/><h2>选择一份内容，开始查看。</h2><p>同一页面呈现文案、素材、修改对照和审核记录。</p></div>:<><section className="panel"><div className="detail-top"><span className={'status '+d.state}>{states[d.state]}</span><span>{p.ageBand} 岁 · {p.locale} · {p.task}</span></div><h2>{p.copy.title}</h2><p className="muted">{p.version} · 第 {d.round} 稿 · 当前操作版本 {d.version}</p><div className="workflow">{['编辑','方法审核','语言审核','发布预览'].map((s,i)=><span key={s}><b>{i+1}</b>{s}</span>)}</div>{d.candidate_hash&&<label className="hash-label">本轮审核绑定的内容摘要<code>{d.candidate_hash}</code></label>}</section>
      {user.role==='editor'&&d.author===user.id&&['draft','changes-requested'].includes(d.state)?<section className="panel"><h3>编辑本稿</h3><form key={`${d.id}:${d.version}:${formReset}`} className="form-stack" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),copy={...p.copy};for(const k of Object.keys(copyLabels) as (keyof typeof copyLabels)[])copy[k]=String(f.get(k));void safely(()=>act('/drafts/'+d.id,'PATCH',{version:f.get('version'),copy,removeAudio:f.get('removeAudio')==='on'},d.version));}}><label>内容版本<input name="version" defaultValue={p.version} required/></label>{Object.entries(copyLabels).map(([key,label])=><label key={key}>{label}<textarea name={key} defaultValue={String(p.copy[key as keyof typeof p.copy])} required maxLength={1000} rows={key==='title'?1:3}/></label>)}{p.audio&&<label className="check"><input type="checkbox" name="removeAudio"/>移除当前语音与对应文件引用，待新版声音制作后再接入。</label>}<button className="primary" disabled={pending}>保存修改</button></form>{dirty&&<div className="notice"><p>本稿有未保存修改。保存后才能提交审核。</p><button className="text-button" onClick={()=>{setDirty(false);setFormReset(v=>v+1);}}>放弃未保存的修改</button></div>}{d.state==='draft'&&<div className="submit-box"><p>保存完毕后提交。提交会冻结这一稿，审核期间不能修改。</p><button className="quiet" disabled={pending||dirty} onClick={()=>void safely(()=>act('/drafts/'+d.id+'/submit','POST',{},d.version))}>冻结并提交审核<ArrowRight size={17}/></button></div>}</section>:<section className="panel"><h3>孩子会看到的内容</h3><dl className="copy-preview">{Object.entries(copyLabels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(p.copy[key as keyof typeof p.copy])}</dd></div>)}</dl></section>}
      <section className="panel"><h3>与来源版本的对照</h3><p className="muted">来源：{selected.source.version}。未变化的文案折叠在原有内容中。</p>{Object.keys(copyLabels).filter(k=>p.copy[k as keyof typeof p.copy]!==selected.source.copy[k as keyof typeof p.copy]).map(k=><div className="difference" key={k}><strong>{copyLabels[k as keyof typeof copyLabels]}</strong><p className="before">原：{String(selected.source.copy[k as keyof typeof p.copy])}</p><p>本稿：{String(p.copy[k as keyof typeof p.copy])}</p></div>)}<p className="muted">固定语音：{p.audio?'保留；字幕须与指定文案完全一致':'未配置。页面使用文字说明，不自动合成声音。'}</p></section>
      <section className="panel"><h3>图像与固定语音 <span className="muted">{p.assets.length} 份</span></h3><div className="assets">{p.assets.map(a=><article className="asset" key={a.id}><div className="asset-top">{a.mime==='audio/mpeg'?<Headphones size={18}/>:<ImageIcon size={18}/>}<strong>{a.id}</strong><small>{Math.round(a.bytes/1024)} KB</small></div>{a.mime==='image/png'?<img src={'/api/studio/media/'+a.path.split('/').at(-1)} alt={a.id+' 审核图集'}/>:<><ReviewAudio src={'/api/studio/media/'+a.path.split('/').at(-1)} onComplete={()=>setPlayedAudio(current=>current.key===reviewKey?{key:reviewKey,hashes:current.hashes.includes(a.sha256)?current.hashes:[...current.hashes,a.sha256]}:{key:reviewKey,hashes:[a.sha256]})}/><p>{a.transcript}</p><small>{a.locale} · {a.voice} · {reviewedAudio.includes(a.sha256)?'本轮已完整试听':'本轮尚未完整试听'}</small></>}<details><summary>来源与文件摘要</summary><p>{a.provenance}</p><code>{a.sha256}</code></details>{selected.mediaSources.filter(m=>a.provenance.startsWith('studio:'+m.id+';')).map(m=><MediaProvenance key={m.id} metadata={m.metadata} inspection={m.inspection}/>)}</article>)}</div>{!p.assets.length&&<p className="muted">此组合使用应用内受限图形，无额外图片或音频文件。</p>}</section>
      {user.role==='editor'&&d.author===user.id&&['draft','changes-requested'].includes(d.state)&&<section className="panel"><h3>从素材库换用文件</h3><p className="muted">先保存文案。声音必须逐字匹配本稿规则；每次换用素材将进入新稿次。</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),item=library.find(m=>m.id===f.get('mediaId'));if(item)void safely(()=>act('/drafts/'+d.id+'/assets','POST',{mediaId:item.id,slot:item.metadata.kind},d.version));}}><label>适用于本稿的已检查素材<select name="mediaId" required defaultValue=""><option value="" disabled>请选择素材</option>{library.filter(m=>m.state==='ready'&&m.metadata.ageBands.includes(p.ageBand)&&(m.metadata.kind==='guide'?m.metadata.locale===p.locale&&m.metadata.transcript===p.copy.rule:p.assets.some(a=>a.id===m.metadata.kind))).map(m=><option value={m.id} key={m.id}>{m.metadata.name} · {m.metadata.kind==='guide'?'声音':'图集'} · {m.id.slice(0,8)}</option>)}</select></label><button className="quiet" disabled={pending||dirty}>换用并开启新稿</button></form><button className="text-button" disabled={pending||dirty} onClick={()=>setTab('library')}>去素材库导入新文件</button></section>}
      {d.candidate_hash&&['in-review','ready','published'].includes(d.state)&&<section className="panel preview-panel"><span className="eyebrow">PLAY THE FROZEN VERSION</span><h3>试玩孩子实际使用的这一稿</h3><p>使用家庭 Web 的完整任务界面与协议。操作只作为内容审核记录，不进入儿童档案或课程。通过审核前，须用当前身份完成至少一次当前稿的完整试玩。</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void safely(async()=>{const data={confirmHash:d.candidate_hash,level:Number(f.get('level')),seed:f.get('seed'),environment:environmentFor(String(f.get('input')) as 'pointer'|'touch'|'keyboard')},body=JSON.stringify({actor:user.id,id:d.id,version:d.version,data}),scope=identity.current;if(previewAttempt.current?.body!==body)previewAttempt.current={body,key:crypto.randomUUID()};const run=await request<CandidatePreview>('/drafts/'+d.id+'/preview','POST',data,{'Idempotency-Key':previewAttempt.current.key,'If-Match':`"${d.version}"`});if(scope!==identity.current)return;previewAttempt.current=null;location.assign('/preview/'+run.id);});}}><div className="preview-options"><label>难度<select name="level" defaultValue="1"><option value="1">1 · 起始</option><option value="2">2 · 进阶</option><option value="3">3 · 挑战</option></select></label><label>操作方式<select name="input" defaultValue="pointer"><option value="pointer">鼠标 / 触控板</option><option value="touch">触屏</option><option value="keyboard">键盘</option></select></label></div><label>题目种子<input name="seed" defaultValue="review-scenario-1" maxLength={80} required/></label><button className="primary" disabled={pending}>准备并进入候选试玩<ArrowRight size={18}/></button></form><p className="muted">相同种子与条件可复现题目；仍需另行检查其他难度、年龄、设备和声音。</p>{selected.previews.length>0&&<div className="preview-runs"><h3>当前可见的试玩记录</h3>{selected.previews.slice(0,12).map(r=><article key={r.id}><strong>第 {r.round} 稿 · 难度 {r.level} · {r.actor===user.id?'我的试玩':'另一审核身份'}</strong><p>{r.receipt?.complete?'完整试玩已核对':r.receipt?'提前结束，不满足通过条件':'尚未核对结束'} · {r.seed} · {r.environment.input}</p><small>试玩编号：<code>{r.id}</code></small><small>{r.pack_hash===d.candidate_hash&&r.round===d.round?'当前稿':'历史稿，不能用于本轮审核'}</small>{r.receipt&&<p>正式步骤 {r.receipt.formalTrials} · 技术排除 {r.receipt.invalidations} · 中断 {r.receipt.interruptions}</p>}</article>)}</div>}</section>}
      {user.role==='editor'&&d.author===user.id&&['in-review','ready'].includes(d.state)&&<section className="panel"><h3>需要修改这一稿？</h3><p>撤回后重新编辑。已有审核和试玩保留在历史中，但不能用于新稿。</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void safely(()=>act('/drafts/'+d.id+'/reopen','POST',{reason:f.get('reason')},d.version));}}><label>撤回与重审原因<textarea name="reason" required minLength={20} maxLength={700}/></label><button className="quiet" disabled={pending}>撤回本稿并重新编辑</button></form></section>}
      {['method-reviewer','language-reviewer'].includes(user.role)&&d.state==='in-review'&&!selected.reviews.some(r=>r.round===d.round&&r.role===user.role)&&<section className="panel review-panel"><span className="eyebrow">INDEPENDENT REVIEW</span><h3>{roleNames[user.role]}决定</h3><p>请实际核对文案与素材，并记录依据。每段声音须在本页完整播放，审核会绑定已听文件的摘要。通过只对当前摘要有效，不能替代适龄试用或效果研究。</p><form key={d.id+':'+d.version} className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void safely(()=>act('/drafts/'+d.id+'/review','POST',{decision:f.get('decision'),note:f.get('note'),...(f.get('previewId')?{previewId:f.get('previewId')}:{}),checks:Object.fromEntries(['instructions','ageAndLanguage','assets','claims'].map(k=>[k,f.get(k)==='on'])),audioReviewedHashes:reviewedAudio},d.version));}}>{[['instructions','规则、操作与判定一致，孩子能理解该做什么。'],['ageAndLanguage','已核对当前年龄段、语言与文化适用性。'],['assets','已查看图像，并试听所有配置的声音，确认音文相符。'],['claims','提示与生活实践没有未经证实的诊断或疗效承诺。']].map(([k,label])=><label className="check" key={k}><input type="checkbox" name={k}/>{label}</label>)}<label>审核依据与需要修改的地方<textarea name="note" required minLength={20} maxLength={700} rows={4} placeholder="至少 20 个字符，说明检查了什么、依据及问题。"/></label><label>当前身份的完整试玩记录<select name="previewId" defaultValue=""><option value="">退回修改可不选择；通过须选择</option>{selected.previews.filter(r=>r.actor===user.id&&r.round===d.round&&r.pack_hash===d.candidate_hash&&r.receipt?.complete).map(r=><option key={r.id} value={r.id}>难度 {r.level} · {r.seed} · {r.id.slice(0,8)}</option>)}</select></label><label>决定<select name="decision" defaultValue="changes"><option value="changes">退回修改</option><option value="approve">通过这一稿</option></select></label><button className="primary" disabled={pending}>提交审核决定</button></form></section>}
      {user.role==='publisher'&&d.state==='ready'&&<section className="panel publish-panel"><h3>发布为本地审核预览</h3><p>本地家庭的新练习将选用此版本。进行中的练习保留原版本；本操作不开放任何商业国家或地区。</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void safely(()=>act('/drafts/'+d.id+'/publish','POST',{confirmHash:f.get('hash'),days:Number(f.get('days'))},d.version));}}><label>核对并填写内容摘要<input name="hash" required pattern="[a-f0-9]{64}" autoComplete="off"/></label><label>预览有效天数<input name="days" type="number" min={1} max={30} defaultValue={7} required/></label><button className="primary" disabled={pending}>签名并发布本地预览</button></form></section>}
      {user.role==='publisher'&&['published','recalled'].includes(d.state)&&<section className="panel recall-panel"><h3>{d.state==='recalled'?'重试召回清理':'召回这一预览版本'}</h3><p>新练习与关联补传将被拒绝，活动练习会停止。断网设备只能在重新连接后收到变更。</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void safely(()=>act('/drafts/'+d.id+'/recall','POST',{confirmHash:f.get('hash'),reason:f.get('reason')},d.version));}}><label>已发布摘要<code>{d.published_hash}</code><input name="hash" required pattern="[a-f0-9]{64}" autoComplete="off" placeholder="填写上面的完整摘要确认"/></label><label>召回原因<textarea name="reason" minLength={10} maxLength={500} required rows={3}/></label><button className="danger" disabled={pending}>确认召回并停止使用</button></form></section>}
      <section className="panel"><h3><History size={18}/> 审核与操作记录</h3>{selected.reviews.map(r=><article className="review-record" key={r.id}><span className="status">第 {r.round} 稿 · {r.decision==='approve'?'通过':'退回'}</span><strong>{r.name} · {roleNames[r.role]}</strong><p>{r.note}</p>{r.preview_id&&<p className="muted">绑定试玩：<code>{r.preview_id}</code></p>}{r.checks?.audioReviewedHashes?.length?<p className="muted">已确认声音：{r.checks.audioReviewedHashes.map(hash=><code key={hash}>{hash} </code>)}</p>:null}<small>{new Date(r.created_at).toLocaleString()}</small></article>)}<ol className="timeline">{selected.history.map((a,i)=><li key={i}><strong>{actions[a.action]??a.action}</strong><span>{a.name} · {new Date(a.at).toLocaleString()}</span></li>)}</ol></section>
    </>}</section></div>}
    <footer>专注岛内容工作台 · 真实审核应由团队中具备对应职责的专业人员完成。</footer></main></div></div>;
}
