import {useRef,useState} from 'react';
import {Upload,Image as ImageIcon,Headphones,ShieldCheck} from 'lucide-react';
import {MEDIA_UPLOAD_LIMIT,mediaMime,mediaPath} from '../../../packages/content/media-library.ts';
import type {LibraryMedia,MediaMetadata} from '../../../packages/content/media-library.ts';
export type StudioRequest=<T>(path:string,method?:string,data?:unknown,headers?:Record<string,string>)=>Promise<T>;
interface Props {items:LibraryMedia[];canEdit:boolean;pending:boolean;request:StudioRequest;upload:(path:string,file:File,mime:string)=>Promise<LibraryMedia>;run:(fn:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<void>;onDirty:(value:boolean)=>void}
export function MediaLibrary({items,canEdit,pending,request,upload,run,refresh,onDirty}:Props){
  const [kind,setKind]=useState<MediaMetadata['kind']>('characters'),[file,setFile]=useState<File|null>(null),[step,setStep]=useState(''),[latest,setLatest]=useState<string|null>(null);
  const attempt=useRef<{body:string;key:string}|null>(null);
  return <div className="library-layout"><section className="panel library-intro"><span className="eyebrow">A HOME FOR EVERY ASSET</span><h2>让图像、声音和来源一起入库。</h2><p>导入后先查看处理结果，再回到可编辑稿件中使用。每次换素材都会开启新稿次，随后重新试玩和审核。</p><p className="muted">当前支持任务四格 PNG 图集和固定 MP3 指引。语音在制作阶段完成，应用只播放已有文件。</p></section>
    {canEdit&&<section className="panel"><h3><Upload size={19}/>导入一份素材</h3><form className="form-stack" onChange={()=>onDirty(true)} onSubmit={e=>{
      e.preventDefault();const fields=new FormData(e.currentTarget),chosen=file;
      void run(async()=>{
        if(!chosen)throw new Error('请先选择要导入的文件。');if(chosen.size>MEDIA_UPLOAD_LIMIT)throw new Error('文件不能超过 5 MB。');if(!fields.getAll('ageBands').length)throw new Error('请至少选择一个制作时面向的年龄段。');
        setStep('正在核对文件');setLatest(null);
        try{
          const metadata={kind,name:String(fields.get('name')),source:String(fields.get('source')),rights:String(fields.get('rights')),rightsConfirmed:fields.get('rightsConfirmed')==='on',ageBands:fields.getAll('ageBands'),...(kind==='guide'?{locale:fields.get('locale'),voice:String(fields.get('voice')),transcript:String(fields.get('transcript'))}:{layoutConfirmed:fields.get('layoutConfirmed')==='on'})};
          const bytes=await chosen.arrayBuffer(),sourceHash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');
          const data={metadata,sourceHash,sourceBytes:chosen.size},body=JSON.stringify(data);if(attempt.current?.body!==body)attempt.current={body,key:crypto.randomUUID()};
          const created=await request<LibraryMedia>('/media-imports','POST',data,{'Idempotency-Key':attempt.current.key});
          if(created.state==='rejected')throw new Error('这份导入未通过检查。修正文件后重新选择，再建立新的导入。');
          setStep('正在上传并检查格式');const saved=created.state==='ready'?created:await upload('/media-imports/'+created.id+'/file',chosen,mediaMime(kind));
          await refresh();onDirty(false);setLatest(saved.id);setStep('检查完成，请核对下方文件与来源说明。');attempt.current=null;
        }catch(error){setStep('导入尚未完成。保留原文件和说明后可重试；文件无效时请重新导出并选择。');throw error;}
      });
    }}><fieldset disabled={pending}><div className="preview-options"><label>素材用途<select value={kind} onChange={e=>{setKind(e.target.value as MediaMetadata['kind']);setFile(null);setStep('');attempt.current=null;}}><option value="characters">动物四格图集</option><option value="objects">物品四格图集</option><option value="guide">任务规则声音</option></select></label><label>素材名称<input name="name" required minLength={2} maxLength={100} placeholder="例如 英语 6–8 岁搜索规则"/></label></div>
      <label>选择文件<input key={kind} type="file" accept={kind==='guide'?'.mp3,audio/mpeg':'.png,image/png'} required onChange={e=>{setFile(e.target.files?.[0]??null);attempt.current=null;setLatest(null);}}/></label><p className="muted">单份最多 5 MB。{kind==='guide'?'MP3 时长 0.2–120 秒；保留音频帧，移除封面与标签。':'正方形静态 PNG，边长 256–2048 且为偶数；每格占一半，不自动裁切或换序。'}</p>
      {kind!=='guide'&&<div className="atlas-help"><strong>从左上开始，按行放置</strong><ol>{(kind==='characters'?['小兔','狐狸','小熊','小猫']:['苹果','叶子','花朵','莓果']).map(s=><li key={s}>{s}</li>)}</ol><label className="check"><input type="checkbox" name="layoutConfirmed" required/>我已逐格核对图像与上述顺序，图像主体没有跨格。</label></div>}
      <div className="age-options"><span>制作时面向的年龄</span>{['6-8','9-11','12-14','15-17'].map(age=><label className="check" key={age}><input name="ageBands" type="checkbox" value={age}/>{age} 岁</label>)}</div>
      {kind==='guide'&&<><div className="preview-options"><label>语音语言<select name="locale"><option value="zh-CN">简体中文</option><option value="en">English</option></select></label><label>音色 / 录制说明<input name="voice" required minLength={2} maxLength={120} placeholder="例如 zh-CN-XiaoxiaoNeural"/></label></div><label>逐字字幕<textarea name="transcript" required maxLength={1000} rows={3} placeholder="须与稿件完整规则逐字一致；系统不自动识别录音文字。"/></label></>}
      <label>制作来源<textarea name="source" required minLength={10} maxLength={500} rows={2} placeholder="记录制作人、工具/版本和原始文件归档位置；不要填写 API Key。"/></label><label>使用权依据<textarea name="rights" required minLength={10} maxLength={500} rows={2} placeholder="记录自制、授权合同或供应商条款的依据和团队内凭证位置。"/></label><label className="check"><input name="rightsConfirmed" type="checkbox" required/>我已核对使用权与录制授权依据，并将原始凭证保存在团队档案中。</label>
      <button className="primary" disabled={pending||!file}><Upload size={17}/>{pending?'正在处理素材…':'导入并检查'}</button><button type="reset" className="text-button" onClick={()=>{setKind('characters');setFile(null);setStep('');setLatest(null);attempt.current=null;onDirty(false);}}>放弃尚未提交的填写内容</button></fieldset></form>{step&&<p className={latest?'notice':'muted'} role="status">{step}</p>}
    </section>}
    <section className="panel"><div className="queue-title"><h3>素材库</h3><span>{items.length} / 最近 100 份</span></div><p className="muted">“检查通过”只表示文件技术检查通过。内容、听感、顺序与适龄性仍需专业审核。</p>{!items.length&&<div className="empty"><ImageIcon size={28}/><p>还没有团队导入的素材。</p></div>}<div className="library-grid">{items.map(item=><article className={'library-card '+(latest===item.id?'new-asset':'')} key={item.id}><div className="asset-top">{item.metadata.kind==='guide'?<Headphones size={19}/>:<ImageIcon size={19}/>}<strong>{item.metadata.name}</strong><span className="status">{item.state==='ready'?'检查通过，待审稿':item.state==='rejected'?'文件未通过':'等待上传'}</span></div><p className="muted">{item.metadata.ageBands.join('、')} 岁{item.metadata.kind==='guide'?' · '+item.metadata.locale:''}</p>
    {item.state==='ready'&&item.asset_hash&&item.inspection&&<>{item.metadata.kind==='guide'?<audio controls preload="none" src={'/api/studio/media/'+mediaPath(item.asset_hash,item.inspection.mime).split('/').at(-1)}/>:<img src={'/api/studio/media/'+mediaPath(item.asset_hash,item.inspection.mime).split('/').at(-1)} alt={item.metadata.name+' 四格图集'}/>}<p>{item.inspection.width?`${item.inspection.width} × ${item.inspection.height}`:`${((item.inspection.durationMs??0)/1000).toFixed(2)} 秒`} · {Math.ceil((item.asset_bytes??0)/1024)} KB</p>{item.metadata.kind==='guide'&&<p className="transcript">{item.metadata.transcript}</p>}</>}
    {item.rejection&&<p className="error">检查代码：{item.rejection}。修正后重新选择文件导入。</p>}<MediaProvenance metadata={item.metadata} inspection={item.inspection}/><details><summary>导入与文件编号</summary><p>导入：<code>{item.id}</code></p><p>原文件：<code>{item.source_hash}</code></p>{item.asset_hash&&<p>交付文件：<code>{item.asset_hash}</code></p>}</details></article>)}</div></section>
  </div>;
}
export function MediaProvenance({metadata,inspection}:{metadata:MediaMetadata;inspection:LibraryMedia['inspection']}){return <details className="media-provenance"><summary><ShieldCheck size={14}/>制作来源与使用权声明</summary><dl><dt>制作来源</dt><dd>{metadata.source}</dd><dt>使用权依据</dt><dd>{metadata.rights}</dd><dt>技术处理</dt><dd>{inspection?.processor??'尚未检查'}</dd>{inspection?.rmsDbfs!==undefined&&<><dt>分析值（24 kHz 单声道解码）</dt><dd>平均电平 {inspection.rmsDbfs} dBFS · 采样峰值 {inspection.peakDbfs} dBFS。用于发现异常，不能代替响度标准或听审。</dd></>}</dl></details>;}
