import { useEffect,useRef,useState } from 'react';
import type { FamilyPack } from '../../../packages/family-support/publication.ts';
import type { SupportDraft } from '../../api/support-studio.ts';
import type { Words } from '../../../packages/family-support/model.ts';
import './support-content.css';

type User={id:string;role:'editor'|'method-reviewer'|'language-reviewer'|'publisher'};
type Request=<T>(path:string,method?:string,data?:unknown,headers?:Record<string,string>)=>Promise<T>;
type Listing={drafts:{id:string;age_band:string;content_version:string;state:string;round:number}[];releases:{hash:string;version:string;state:string;age_band:string;channel:string}[]};
type Detail={draft:SupportDraft;source:FamilyPack;reviews:{id:string;reviewer:string;round:number;scope:string;decision:string;note:string;name:string}[];history:{action:string;at:string;name:string}[]};
const states:Record<string,string>={draft:'编辑中','in-review':'三项审阅中','changes-requested':'需要修改',ready:'可发布预览',published:'已发布预览',recalled:'已召回'};
const scopes={'method':'方法审阅','language:zh-CN':'中文审阅','language:en':'英文审阅'};
const fields:Record<string,string>={title:'标题',purpose:'这一节做什么',invitation:'邀请语',example:'分龄示例',steps:'操作步骤',fallback:'遇到困难时',notice:'观察提示',parentTip:'家长提示'};
const ordered=(value:object)=>Object.keys(fields).filter(key=>key in value).map(key=>[key,(value as Record<string,Words|Words[]>)[key]] as const);
const actionLabels:Record<string,string>={created:'建立版本',edited:'修改稿件',submitted:'冻结送审',reviewed:'完成审阅',reopened:'撤回编辑',published:'发布本地预览',recalled:'召回版本'};
const checksCopy={ageAppropriate:'适合本年龄的理解能力与生活情境',choiceAndRest:'保留孩子选择、求助、休息和退出',claims:'没有未经验证的效果主张或诊断表述',language:'文字清晰，双语意思对应，未增加要求'};
const sections=[...Array.from({length:9},(_,i)=>`lesson:${i}`),...['find','turns','steps','return'].map(id=>`template:${id}`)];
export function SupportContent({user,request,run,pending,onDirty}:{user:User;request:Request;run(fn:()=>Promise<void>):Promise<void>;pending:boolean;onDirty(dirty:boolean):void}){
  const [list,setList]=useState<Listing>({drafts:[],releases:[]}),[detail,setDetail]=useState<Detail|null>(null),[pack,setPack]=useState<FamilyPack|null>(null);
  const [dirty,setDirty]=useState(false),[section,setSection]=useState(0),[locale,setLocale]=useState<'zh-CN'|'en'>('zh-CN'),[read,setRead]=useState<string[]>([]),[scope,setScope]=useState<keyof typeof scopes>(user.role==='method-reviewer'?'method':'language:zh-CN');
  const [note,setNote]=useState(''),[checks,setChecks]=useState<Record<keyof typeof checksCopy,boolean>>({ageAppropriate:false,choiceAndRest:false,claims:false,language:false});
  const [message,setMessage]=useState('');const alive=useRef(true),attempt=useRef<{fingerprint:string;key:string}|null>(null);
  function mark(value:boolean){setDirty(value);onDirty(value);}
  async function refresh(){const result=await request<Listing>('/support');if(alive.current)setList(result);}
  useEffect(()=>{alive.current=true;void run(refresh);return()=>{alive.current=false;onDirty(false);};},[]);
  function display(value:Detail){setDetail(value);setPack(structuredClone(value.draft.pack));setRead([]);setNote('');setChecks({ageAppropriate:false,choiceAndRest:false,claims:false,language:false});mark(false);}
  async function open(id:string){if(dirty)return;await run(async()=>{const next=await request<Detail>('/support/'+id);if(alive.current){display(next);setMessage('');}});}
  async function command(path:string,method:string,input:unknown,version?:number){
    const fingerprint=JSON.stringify({path,method,input,version});if(attempt.current?.fingerprint!==fingerprint)attempt.current={fingerprint,key:crypto.randomUUID()};
    await run(async()=>{const result=await request<Detail>(path,method,input,{'Idempotency-Key':attempt.current!.key,...(version?{'If-Match':`"${version}"`}:{})});if(!alive.current)return;attempt.current=null;display(result);setMessage('已保存，审阅与发布均绑定这份内容版本。');await refresh();});
  }
  const d=detail?.draft,editable=!!d&&user.role==='editor'&&d.author===user.id&&['draft','changes-requested'].includes(d.state);
  const selected=pack?(section<9?pack.lessons[section]:pack.templates[section-9]):null;
  const source=detail?(section<9?detail.source.lessons[section]:detail.source.templates[section-9]):null;
  const completed=detail?.reviews.filter(r=>r.round===d?.round&&r.decision==='approve')??[];
  const canReview=d?.state==='in-review'&&['method-reviewer','language-reviewer'].includes(user.role)&&!completed.some(r=>r.reviewer===user.id);
  function edit(key:string,value:string,index?:number){if(!pack||!editable)return;const next=structuredClone(pack),target=(section<9?next.lessons[section]:next.templates[section-9]) as unknown as Record<string,Words|Words[]>;if(index===undefined)(target[key] as Words)[locale]=value;else (target[key] as Words[])[index][locale]=value;setPack(next);mark(true);}
  function changeScope(value:keyof typeof scopes){setScope(value);if(value!=='method')setLocale(value==='language:en'?'en':'zh-CN');setRead([]);setNote('');setChecks({ageAppropriate:false,choiceAndRest:false,claims:false,language:false});mark(true);}
  return <div className="support-content">
    <section className="panel support-intro"><h2>家长课与生活任务</h2><p>每个年龄包包含九节家长课、四个生活模板及中英双语。方法、中文、英文由三位不同人员审阅，发布人再确认；账号职责不等同于专业资质认证。</p><p className="muted">只发布本地预览。逐节勾选记录审阅者的阅读声明，不代表系统证明其认真阅读或内容有效。</p></section>
    {message&&<p className="notice" role="status">{message}</p>}
    <div className="support-columns"><aside className="panel support-queue"><h2>版本队列</h2><button className="quiet" disabled={pending||dirty} onClick={()=>void run(async()=>{await refresh();if(d){const fresh=await request<Detail>('/support/'+d.id);if(alive.current)display(fresh);}})}>重新读取</button>
      {list.drafts.length===0&&<p className="muted">还没有编辑稿件。</p>}{list.drafts.map(row=><button key={row.id} className={'queue-item '+(row.id===d?.id?'selected':'')} disabled={pending||dirty} onClick={()=>void open(row.id)}><span className={'status '+row.state}>{states[row.state]}</span><strong>{row.age_band} 岁 · 中英双语</strong><span>{row.content_version} · 第 {row.round} 轮</span></button>)}
      {user.role==='editor'&&<form className="form-stack support-new" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void command('/support','POST',{sourceHash:f.get('source'),version:f.get('version')});}}><h3>建立新版本</h3><label>内容来源<select name="source" required disabled={pending||dirty}>{list.releases.filter(r=>r.state==='active').map(r=><option key={r.hash} value={r.hash}>{r.age_band} 岁 · {r.version}</option>)}</select></label><label>新版本号<input name="version" placeholder="例如 1.1.0-preview" required maxLength={80} disabled={pending||dirty}/></label><button className="primary" disabled={pending||dirty||!list.releases.length}>建立稿件</button></form>}
    </aside><section className="panel support-detail">{!d||!pack||!selected?<div className="support-empty"><h2>选择一份稿件</h2><p>按年龄审阅完整的陪伴内容与生活活动。新版本不会改写过去的家庭记录。</p></div>:<>
      <div className="support-heading"><div><span className={'status '+d.state}>{states[d.state]}</span><h2>{pack.ageBand} 岁的家庭支持内容</h2><p>{pack.version} · 第 {d.round} 轮 · 9 节课 / 4 个模板</p></div>{dirty&&<button className="quiet" disabled={pending} onClick={()=>display(detail!)}>放弃未保存的修改</button>}</div>
      {d.candidate_hash&&<details><summary>当前候选内容摘要</summary><code className="support-hash">{d.candidate_hash}</code></details>}
      <div className="support-status">{Object.entries(scopes).map(([key,label])=><span key={key}>{label}：{completed.some(r=>r.scope===key)?'已通过':'待审阅'}</span>)}</div>
      <div className="support-reading"><label>章节<select value={section} onChange={e=>setSection(Number(e.target.value))}>{pack.lessons.map((l,i)=><option key={i} value={i}>{read.includes(sections[i])?'✓ ':''}家长课 {i} · {l.title[locale]}</option>)}{pack.templates.map((t,i)=><option key={t.id} value={i+9}>{read.includes(sections[i+9])?'✓ ':''}生活任务 · {t.title[locale]}</option>)}</select></label><label>显示语言<select value={locale} onChange={e=>setLocale(e.target.value as typeof locale)}><option value="zh-CN">简体中文</option><option value="en">English</option></select></label></div>
      <fieldset className="form-stack support-fields" disabled={pending}>{ordered(selected).map(([key,value])=><div key={key}>{(Array.isArray(value)?value:[value]).map((words:Words,i:number)=><label key={i}>{fields[key]}{Array.isArray(value)?` ${i+1}`:''}{editable?<textarea value={words[locale]} rows={key==='title'?2:3} maxLength={1000} onChange={e=>edit(key,e.target.value,Array.isArray(value)?i:undefined)}/>:<p className="support-text" lang={locale}>{words[locale]}</p>}</label>)}</div>)}</fieldset>
      <details className="support-source"><summary>对照来源版本 {detail!.source.version}</summary>{source&&ordered(source).map(([key,value])=><div key={key}><h4>{fields[key]}</h4>{(Array.isArray(value)?value:[value]).map((w:Words,i:number)=><p key={i} lang={locale}>{w[locale]}</p>)}</div>)}</details>
      {editable&&<div className="support-actions"><button className="primary" disabled={pending||!dirty} onClick={()=>void command('/support/'+d.id,'PATCH',pack,d.version)}>保存这一稿</button><button className="quiet" disabled={pending||dirty||d.state!=='draft'} onClick={()=>void command('/support/'+d.id+'/submit','POST',{},d.version)}>冻结完整版本并送审</button></div>}
      {canReview&&<form className="form-stack support-review" onSubmit={e=>{e.preventDefault();void command('/support/'+d.id+'/review','POST',{scope,decision:(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')??'changes',note,sections:read,checks},d.version);}}><h3>审阅当前冻结版本</h3><label>审阅职责<select value={scope} onChange={e=>changeScope(e.target.value as typeof scope)} disabled={pending}>{Object.entries(scopes).filter(([key])=>(key==='method')===(user.role==='method-reviewer')).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="support-check"><input type="checkbox" checked={read.includes(sections[section])} disabled={pending||(scope!=='method'&&locale!==(scope==='language:en'?'en':'zh-CN'))} onChange={e=>{setRead(current=>e.target.checked?[...current,sections[section]]:current.filter(x=>x!==sections[section]));mark(true);}}/>我已阅读本节及相关步骤与提示（{read.length} / 13）</label>{Object.entries(checksCopy).map(([key,label])=><label key={key} className="support-check"><input type="checkbox" checked={checks[key as keyof typeof checks]} disabled={pending} onChange={e=>{setChecks({...checks,[key]:e.target.checked});mark(true);}}/>{label}</label>)}<label>审阅依据与需要说明的问题<textarea value={note} onChange={e=>{setNote(e.target.value);mark(true);}} rows={4} minLength={20} maxLength={700} required disabled={pending}/></label><div className="support-actions"><button className="primary" value="approve" disabled={pending||read.length!==13||!Object.values(checks).every(Boolean)||completed.some(r=>r.scope===scope)}>签署本项审阅通过</button><button className="quiet" value="changes" disabled={pending}>退回修改</button></div></form>}
      {user.role==='editor'&&d.author===user.id&&['in-review','ready'].includes(d.state)&&<form className="form-stack support-review" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void command('/support/'+d.id+'/reopen','POST',{reason:f.get('reason')},d.version);}}><h3>撤回后重新编辑</h3><p>撤回会开始新一轮审阅，旧批准不再适用。</p><label>修改原因<textarea name="reason" minLength={20} maxLength={700} required disabled={pending} onChange={()=>mark(true)}/></label><button className="quiet" disabled={pending}>撤回稿件</button></form>}
      {user.role==='publisher'&&['ready','published'].includes(d.state)&&<form className="form-stack support-review" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),publishing=d.state==='ready';void command('/support/'+d.id+(publishing?'/publish':'/recall'),'POST',publishing?{confirmHash:f.get('hash'),days:Number(f.get('days'))}:{confirmHash:f.get('hash'),reason:f.get('reason')},d.version);}}><h3>{d.state==='ready'?'发布本地审核预览':'召回此版本'}</h3><p>{d.state==='ready'?'发布后，此年龄的新指导和新生活目标使用这份版本。历史目标保留原版本。':'召回后停止新使用和继续此版本的目标，保留历史、结束目标和撤回分享。'}</p><label>输入完整内容摘要确认<code className="support-hash">{d.state==='ready'?d.candidate_hash:d.published_hash}</code><input name="hash" required pattern="[a-f0-9]{64}" autoComplete="off" disabled={pending} onChange={()=>mark(true)}/></label>{d.state==='ready'?<label>预览有效天数<input name="days" type="number" min={1} max={30} defaultValue={7} required disabled={pending} onChange={()=>mark(true)}/></label>:<label>召回原因<textarea name="reason" minLength={20} maxLength={700} required disabled={pending} onChange={()=>mark(true)}/></label>}<button className={d.state==='ready'?'primary':'danger'} disabled={pending}>{d.state==='ready'?'确认发布本地预览':'确认召回'}</button></form>}
      <section className="support-history"><h3>审阅与版本记录</h3>{detail!.reviews.map(r=><p key={r.id}><strong>第 {r.round} 轮 · {scopes[r.scope as keyof typeof scopes]} · {r.decision==='approve'?'通过':'退回'} · {r.name}</strong><br/>{r.note}</p>)}{detail!.history.map((h,i)=><p className="muted" key={i}>{h.name} · {actionLabels[h.action]??h.action} · {new Date(h.at).toLocaleString()}</p>)}</section>
    </>}</section></div>
  </div>;
}
